feat: adding register implementation and some changes in .gitignore
hawks-atlanta/gateway-java pull request #35
Opened 2023-09-13 16:13 UTC by SilviaPabon

- I add and update register implementation in ServiceImp, I didn't knew if I should verify some things like the credentials information is in a correct type
- Also, I update .gitignore
- Also I have a question, when ./gradlew run is execute it, there is a way that when we make changes we should't have to execute it again?

2023-09-13 20:51 UTC, Woynert requested changes
Before fixing the issues mentioned get this branch up to date with `dev`.

The following changes where applied: [Add JSON library](https://github.com/hawks-atlanta/gateway-java/pull/37), and [Normalize Status Response](https://github.com/hawks-atlanta/gateway-java/pull/36).

2023-09-13 20:51 UTC, Woynert commented on app/src/main/java/gateway/soap/ServiceImp.java
> +			e.printStackTrace ();
On error, fill the appropiate fields `success` and `message` from [StatusRes](https://github.com/hawks-atlanta/gateway-java/blob/dev/app/src/main/java/gateway/soap/response/StatusRes.java) which [SessionRes](https://github.com/hawks-atlanta/gateway-java/blob/dev/app/src/main/java/gateway/soap/response/SessionRes.java) inherits.

2023-09-15 14:30 UTC, SilviaPabon commented on app/src/main/java/gateway/soap/ServiceImp.java
> +		String url = EnvironmentVar.AUTH_BASEURL + "register";
@Woynert I saw you were working on something about it. I think I'm going to leave this alone until this is modified. AUTH_BASEURL had the host and port of the authentication service, in the other methods the others had to associate a base url as needed, that was my plan, but you can tell me what is most convenient to leave here. I will working on the other thing meanwhile.

2023-09-17 19:12 UTC, Woynert approved these changes
:hammer: Good work!
Squash and merge

2023-09-17 19:36 UTC, merged