test: Add tests for register method
hawks-atlanta/gateway-java pull request #60
Opened 2023-10-03 21:37 UTC by SilviaPabon

@Woynert made the updates for register method previosly, so I just added the tests.
This approved should be close #21

2023-10-04 23:39 UTC, shoriwe commented
How the progress of this has evolved?

2023-10-04 23:58 UTC, SilviaPabon commented
> How the progress of this has evolved? @SilviaPabon

Hi @shoriwe I will mark as ready this PR and another one today.

2023-10-05 03:32 UTC, SilviaPabon commented
@shoriwe Thinking better 💡... I will analyze something about this PR because perhaps I can unite some things about the register with login making something similar to tests that @Woynert implemented in a previous PR, like steps. So, tomorrow I hope that I will concrete this PR 😬

2023-10-05 18:06 UTC, SilviaPabon commented
@Woynert Now this is ready for checking, thanks!

2023-10-06 16:22 UTC, Woynert requested changes
Return 500 on catched error.

2023-10-06 16:23 UTC, Woynert requested changes

2023-10-06 16:23 UTC, Woynert commented on app/src/test/java/gateway/ITServiceAuth.java
> +		Credentials credentialsCopy = credentials;
This is not a copy, but a reference.

2023-10-07 21:57 UTC, PedroChaparro commented
@SilviaPabon, there is a conflict :eyes:

2023-10-08 12:15 UTC, Woynert approved these changes
:octocat:

2023-10-08 13:59 UTC, merged